### ISSUE TITLE
Pipeline - CodeQL

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom-api#203]
* adjust config of the action so that it runs when under the following conditions:
  * PR to main
  * PR to release-FOM-*

**Comment by franTarkenton** [comment]
@DerekRoberts Does this look like what you were thinking?
https://github.com/bcgov/nr-fom-api/blob/feature/codeql/.github/workflows/codeql-analysis.yml

and here is a link to the action being run before I took out the feature branch from the trigger:
https://github.com/bcgov/nr-fom-api/actions/runs/2297035321
