### ISSUE TITLE
Repo re-org kick-off meeting

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom-api#234]
Issues to discuss:

Single vs multiple package.json files

**Comment by basilv** [comment]
FYI one item to be aware of is that we do have code shared between Public and Admin (and ideally would have even more common code between the two). I suspect this is still possible with two separate package.json files, but may get a bit trickier. Might want to think about a third option of one front-end package.json versus one back-end. If possible I'd be interested in participating in a discussion meeting.

**Comment by DerekRoberts** [comment]
Done.
